#!/bin/bash
echo "Running tridiagLU."

ROOT_DIR=$PWD
WALLTIMES_DIR="$ROOT_DIR/walltimes"
TRIDIAG_EXEC="$HOME/Codes/tridiagLU/bin/TRIDIAGLU"
MPI_EXEC="$PETSC_DIR/$PETSC_ARCH/bin/mpiexec"
nproc_max=64

if [ ! -d "$WALLTIMES_DIR" ] ; then
  echo "Creating $WALLTIMES_DIR."
  mkdir $WALLTIMES_DIR
fi

iter=0
while [ $iter -le 10 ]; do
  FILENAME="$WALLTIMES_DIR/walltimes.JacIter_$iter.dat"
  if [ -e "$FILENAME" ] ; then
    rm "$FILENAME"
  fi
  echo "Jacobi iterations: iter = $iter."
  nproc=1
  while [ $nproc -le $nproc_max ] ; do
    echo "  nproc = $nproc."
    DIR_NAME="$ROOT_DIR/JacIter_$iter/nproc_$nproc"
    if [ ! -d "$DIR_NAME" ]; then
      echo "    $DIR_NAME does not exist. Why?"
      cd $ROOT_DIR
    else
      echo "    Reading wall times in $DIR_NAME"
      cd $DIR_NAME
      cat walltimes_tridiagLU.dat >> $FILENAME
      cd $ROOT_DIR
    fi
    let nproc=nproc*2
  done
  let iter=iter+2
done

FILENAME="$WALLTIMES_DIR/walltimes.JacIterNorm.dat"
FILENAME2="$WALLTIMES_DIR/walltimes.ScaLAPACK.dat"
if [ -e "$FILENAME" ] ; then
  rm "$FILENAME"
fi
if [ -e "$FILENAME2" ] ; then
  rm "$FILENAME2"
fi
echo "Jacobi iterations: norm-based exit."
nproc=1
while [ $nproc -le $nproc_max ] ; do
  echo "  nproc = $nproc."
  DIR_NAME="$ROOT_DIR/JacIterNorm/nproc_$nproc"
  if [ ! -d "$DIR_NAME" ]; then
    echo "    $DIR_NAME does not exist. Why?"
    cd $ROOT_DIR
  else
    echo "    Reading wall times in $DIR_NAME"
    cd $DIR_NAME
    cat walltimes_tridiagLU.dat >> $FILENAME
    cat walltimes_tridiagScaLPK.dat >> $FILENAME2
    cd $ROOT_DIR
  fi
  let nproc=nproc*2
done
